# Generated by Django 3.2.16 on 2023-03-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rauan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
